/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomeRenderer: typeof import('./src/components/home/HomeRenderer.vue')['default']
    LinkTo: typeof import('./src/components/LinkTo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RubyText: typeof import('./src/components/RubyText.vue')['default']
  }
}
