/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/friend': RouteRecordInfo<'/friend', '/friend', Record<never, never>, Record<never, never>>,
    '/lab': RouteRecordInfo<'/lab', '/lab', Record<never, never>, Record<never, never>>,
    '/note/': RouteRecordInfo<'/note/', '/note', Record<never, never>, Record<never, never>>,
    '/note/cs/': RouteRecordInfo<'/note/cs/', '/note/cs', Record<never, never>, Record<never, never>>,
    '/note/cs/cldf': RouteRecordInfo<'/note/cs/cldf', '/note/cs/cldf', Record<never, never>, Record<never, never>>,
    '/note/cs/fds': RouteRecordInfo<'/note/cs/fds', '/note/cs/fds', Record<never, never>, Record<never, never>>,
    '/note/math/': RouteRecordInfo<'/note/math/', '/note/math', Record<never, never>, Record<never, never>>,
    '/note/math/LinearAlgebra': RouteRecordInfo<'/note/math/LinearAlgebra', '/note/math/LinearAlgebra', Record<never, never>, Record<never, never>>,
    '/sponsor': RouteRecordInfo<'/sponsor', '/sponsor', Record<never, never>, Record<never, never>>,
    '/sponsorship': RouteRecordInfo<'/sponsorship', '/sponsorship', Record<never, never>, Record<never, never>>,
    '/timeline': RouteRecordInfo<'/timeline', '/timeline', Record<never, never>, Record<never, never>>,
  }
}
