nav:
    - cs:
          - ads:
                - avl-tree
                - amortized-analysis
                - splay-tree
                - red-black-tree
                - b-plus-tree
                - leftist-heaps
                - skew-heaps
          - others:
                - mit-missing-semester
                - c-language-cheatsheet
                - manuals-standards
    - sci:
          - phy:
                - chapter-27
          - prob:
                - chapter-1
          - ma:
                - cheatsheet
                - prove-that
                - completeness-of-real-numbers
          - la:
                - prove-that
                - what-is
    - misc:
          - french
          - test:
                - customToken
                - latex
                - markdown

icon:
    cs: code
    sci: atom
    misc: box-archive
