nav:
    - cs:
          - ads:
                - avl-tree
                - amortized-analysis
                - splay-tree
                - red-black-tree
                - b-plus-tree
          - others:
                - mit-missing-semester
                - c-language-cheatsheet
                - manuals-standards
    - sci:
          - phy:
                - chapter-27
          - ma:
                - cheatsheet
                - prove-that
                - completeness-of-real-numbers
          - la:
                - prove-that
                - what-is
    - misc:
          - french
          - test:
                - customToken
                - latex
                - markdown
