nav:
  - cs:
      - c:
          - snippets
      - test:
          - customToken
          - latex
          - markdown
          - toc
      - ads:
          - avl-tree
          - amortized-analysis
          - splay-tree
          - red-black-tree
          - b-plus-tree
  - math:
      - fourier
      - dm
      - la
  - misc:
      - french
