nav:
    - cs:
          - ads:
                - avl-tree
                - amortized-analysis
                - splay-tree
                - red-black-tree
                - b-plus-tree
    - math:
          - fourier
    - misc:
          - french
          - test:
                - customToken
                - latex
                - markdown
