nav:
  - cs:
      - c:
          - snippets
      - test:
          - customToken
          - latex
          - markdown
          - toc
      - cldf
      - fds
  - math:
      - fourier
      - dm
      - la
