nav:
    - cs:
          - ads:
                - avl-tree
                - amortized-analysis
                - splay-tree
                - red-black-tree
                - b-plus-tree
                - leftist-heap
                - skew-heap
                - binomial-queue
          - others:
                - mit-missing-semester
                - c-language-cheatsheet
                - manuals-standards
    - ctf:
          - game:
                - zjuctf2024
    - sci:
          - phy:
                - chapter-27
                - chapter-28
                - chapter-29-30
          - prob:
                - chapter-1
                - chapter-2
          - ma:
                - cheatsheet
                - prove-that
                - completeness-of-real-numbers
          - la:
                - prove-that
                - what-is
    - misc:
          - french
          - test:
                - customToken
                - latex
                - markdown

icon:
    cs: code
    ctf: flag
    sci: atom
    misc: box-archive
